# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fcst_action',
                'doc_host': 'https://victorymr.github.io',
                'git_url': 'https://github.com/victorymr/fcst_action',
                'lib_path': 'fcst_action'},
  'syms': {'fcst_action.core': {'fcst_action.core.foo': ('core.html#foo', 'fcst_action/core.py')}}}
